name: "Build Docs"
inputs:
  doc-ref:
    description: 'Fully qualified ref to build docs for.'
    required: true
  header-type:
    description: 'Which version of a header should be generated. Options are branch, empty, or tag.'
  doc-name:
    description: 'Name of the ref to be added to the version warning header.'
    required: true
  book-dir:
    description: 'book.toml location'
    required: true
  redirect-url:
    description: 'URL that the version warning header will suggest the user to visit.'
outputs:
  output-dir:
    description: "Directory where documents are generated."
    value: ${{ steps.build-docs.outputs.output-dir }}
runs:
    using: "composite"
    steps:
      - name: PR Environment Logic
        if: ${{ startsWith(inputs.doc-ref, 'refs/pull/') }}
        shell: bash
        run: |
          echo export REF = "${{inputs.doc-name}}"
          echo export REDIRECT = "${{inputs.redirect-url}}"
          "${{ inputs.book-dir }}/theme/header.hbs" < envsubst < "${{ github.action_path }}/branch/header.hbs"
          echo "Building docs from a pull request ${{inputs.doc-ref}}" >> $GITHUB_STEP_SUMMARY
      - name: Main Branch Environment Logic
        if: ${{ startsWith(inputs.doc-ref, 'refs/heads/') }}
        shell: bash
        run: |
          echo export REF = "${{inputs.doc-name}}"
          echo export REDIRECT = "${{inputs.redirect-url}}"
          "${{ inputs.book-dir }}/theme/header.hbs" < envsubst < "${{ github.action_path }}/branch/header.hbs"
          echo "Building docs from a branch ${{inputs.doc-ref}}" >> $GITHUB_STEP_SUMMARY
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install cargo binstall
        uses: cargo-bins/cargo-binstall@main
      - name: Install mdbook
        shell: bash
        run: |
          mkdir mdbook
          curl -sSL https://github.com/rust-lang/mdBook/releases/download/v0.4.40/mdbook-v0.4.40-x86_64-unknown-linux-gnu.tar.gz | tar -xz --directory=mdbook
          echo `pwd`/mdbook/ >> $GITHUB_PATH
      - name: Install mdbook preprocessors
        shell: bash
        run: |
          cargo binstall mdbook-alerts --no-confirm
          cargo binstall mdbook-linkcheck --no-confirm
      - name: Build docs
        id: build-docs
        shell: bash
        run: |
          cd docs-export
          mdbook build ${{inputs.book-dir}}
          echo "output-dir=`pwd`/book/html" >> "$GITHUB_OUTPUT"