name: Docs CI
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Cargo binstall
        uses: cargo-bins/cargo-binstall@main
      - name: Setup mdBook
        run: |
          mkdir mdbook
          curl -sSL https://github.com/rust-lang/mdBook/releases/download/v0.4.14/mdbook-v0.4.40-x86_64-unknown-linux-gnu.tar.gz | tar -xz --directory=./mdbook
          echo `pwd`/mdbook >> $GITHUB_PATH

      - name: Build
        run: |
          cargo binstall mdbook-alerts
      - name: Cargo link check install
        run: |
          mkdir -p mdbook-linkcheck && cd "$_" && \
          curl -L https://github.com/Michael-F-Bryan/mdbook-linkcheck/releases/latest/download/mdbook-linkcheck.x86_64-unknown-linux-gnu.zip -o mdbook-linkcheck.zip && \
          unzip "$_" && \
          chmod +x mdbook-linkcheck && \
          export PATH=$PWD:$PATH && \
          cd ..
      - name: Test md book
        run: |
          cd docs-export
          mdbook build
