name: Docs CI
permissions:
    contents: write
on:
  workflow_dispatch:
  push:
    branches:
        - 'main'
    paths:
        - 'README.md'
        - 'docs/**'
        - 'docs-export/**'
  pull_request:
    branches:
      - 'main'
    paths:
      - 'README.md'
      - 'docs/**'
      - 'docs-export/**'

jobs:
  build:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Build md book
        uses: ./.github/actions/docs_build
        with:
          doc-ref: ${{ github.ref }}
      - name: Deploy to GitHub Pages
        if: ${{github.ref == 'refs/heads/main'}}
        uses: JamesIves/github-pages-deploy-action@v4.6.1
        with:
          folder: docs-export/book/html
          branch: gh-pages
          target-folder: dev
          clean: true
        
                    
