name: Docs CI
permissions:
    contents: write
on:
  workflow_dispatch:
  push:
    branches:
        - 'main'
    paths:
        - 'README.md'
        - 'docs/**'
        - 'docs-export/**'
  pull_request:
    branches:
      - 'main'
    paths:
      - 'README.md'
      - 'docs/**'
      - 'docs-export/**'

jobs:
  build:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout input ref
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}
      - name: Build md book
        id: build-docs
        uses: ./.github/actions/docs_build
        with:
          doc-ref: ${{ github.ref }}
          header-type: "branch"
          doc-name: "dev test"
          book-dir: "docs-export"
          redirect-url: "docs.ue4ss.com"
      - name: Deploy to GitHub Pages
        if: ${{github.ref == 'refs/heads/main'}}
        uses: JamesIves/github-pages-deploy-action@v4.6.1
        with:
          folder: ~${{ steps.build-docs.outputs.output-dir }}
          branch: gh-pages
          target-folder: dev
          clean: true
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: tj-actions/changed-files@v44
      id: changed-files
      with:
        files: '**/*.md'
        separator: ","
    - uses: DavidAnson/markdownlint-cli2-action@v16
      if: steps.changed-files.outputs.any_changed == 'true'
      with:
        globs: ${{ steps.changed-files.outputs.all_changed_files }}
        separator: ","
        
                    
