name: Docs Deploy
permissions:
    contents: write
on:
  workflow_dispatch:
  push:
    branches:
        - 'main'
    tags:
        - 'v**'
    paths:
        - 'README.md'
        - 'docs/**'
        - 'docs-export/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Repo SemVer
        if: ${{github.ref_type == 'tag'}}
        uses: lhstrh/action-repo-semver@v1.1.2
        id: repo-semver
        with: 
            planned: ${{github.ref_name}}
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Cargo binstall
        uses: cargo-bins/cargo-binstall@main
      - name: Setup mdBook
        run: |
          mkdir mdbook
          curl -sSL https://github.com/rust-lang/mdBook/releases/download/v0.4.40/mdbook-v0.4.40-x86_64-unknown-linux-gnu.tar.gz | tar -xz --directory=mdbook

      - name: Build
        run: |
          cargo binstall mdbook-alerts --no-confirm
      - name: Cargo link check install
        run: |
          cargo binstall mdbook-linkcheck --no-confirm


        
      - name: Test md book
        run: |
          cd docs-export
          ../mdbook/mdbook build
        if: ${{github.ref_type == 'tag'}}
        env: 
            MDBOOK_preprocessor__versionwarning__version: "tag"