name: Deploy Docs
on:
    workflow_call:
        inputs:
            docs_config:
                description: "Environment variables to pass to the docs release"
                required: true
                type: string
            git_ref:
                description: "Github ref to deploy docs for"
                required: false
                type: string

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - name: Parse docs config
            run: |
                echo '${{ join(fromJson(inputs.docs_config), ' >> $GITHUB_ENV &&') }} >> $GITHUB_ENV'
          - name: Echo env vars
            run: |
                echo "$MDBOOK_test_env_var"
#          - name: Checkout code
#            uses: actions/checkout@v3
#            with:
#                fetch-depth: 0  
#                ref: ${{ inputs.git_ref }}
#          - name: Setup Python
#            uses: actions/setup-python@v4
#            with:
#                python-version: '3.x'
#          - name: Cargo binstall
#            uses: cargo-bins/cargo-binstall@main
#          - name: Setup mdBook
#            run: |
#                mkdir mdbook
#                curl -sSL https://github.com/rust-lang/mdBook/releases/download/v0.4.40/mdbook-v0.4.40-x86_64-unknown-linux-gnu.tar.gz | tar -xz --directory=mdbook
#          - name: Build
#            run: |
#                cargo binstall mdbook-alerts --no-confirm
#          - name: Cargo link check install
#            run: |
#                cargo binstall mdbook-linkcheck --no-confirm
#          - name: Test md book
#            run: |
#                cd docs-export
#                ../mdbook/mdbook build

  