name: Docs Manual Test
on:
    workflow_dispatch:
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
          - name: Generate variables
            run: |
                echo "[\"MDBOOK_test_env_var=asdf\"]" >> $GITHUB_OUTPUT
    job2:
        needs: test
        uses: ./.github/workflows/docs_deploy_reusable.yml
        with:
            docs_config: ${{ needs.test.outputs }}