name: Create Check
# To trigger the check
on:  
  pull_request:
    branches: [ "main" ]
jobs:
    start-check:
        runs-on: ubuntu-latest     
        permissions:      
            checks: write   # Permission to create a Check Run     
            contents: write # Permission to write a repository_dispatch requests     
        steps:     
            - name: Create Check
              run: exit 1
    success:
        name: Success gate
        if: always()
        needs:
            - start-check
        runs-on: ubuntu-latest
        steps:
            - run: jq --exit-status 'all(.result == "success")' <<< '${{ toJson(needs) }}'
            - name: Done
              run: exit 0