name: Log dwmapi.dll version

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run the workflow on'
        default: 'main'
        required: true

permissions:
  contents: read

jobs:
  make-release:
    permissions: write-all
    runs-on: windows-2022

    steps:
      - name: Log dwmapi.dll version
        run: |
          (Get-Item "C:\Windows\System32\dwmapi.dll").VersionInfo